# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e4b32b740e0465d6d8c3e2a373957119"
name = "wishlist-test"
handle = "wishlist-test-25"
application_url = "https://loops-pursuant-indicating-britannica.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "joel-baby-house.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://loops-pursuant-indicating-britannica.trycloudflare.com/auth/callback",
  "https://loops-pursuant-indicating-britannica.trycloudflare.com/auth/shopify/callback",
  "https://loops-pursuant-indicating-britannica.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
